import csv
import requests

# generated by chatgpt
# this works when i go via browser, but not via this code
# but i have downloaded the data for now and saved
# but that have me looks like all the symbols and not just the sp500


API_KEY = 'RKEC34PXCH65ECDK'  # got on 24-dec-2023 gave my samshinde@gmail.com
API_ENDPOINT = 'https://www.alphavantage.co/query?function=LISTING_STATUS&apikey=' + API_KEY

try:
    # Make API request
    response = requests.get(API_ENDPOINT)
    response.raise_for_status()  # Raise an HTTPError for bad responses

    # Parse the JSON response
    data = response.json()

    # Extract relevant information
    constituents = data.get('data', [])

    # Write to CSV
    with open('sp500_constituents_2.csv', 'w', newline='') as csvfile:
        fieldnames = ['symbol', 'name', 'industry']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for constituent in constituents:
            writer.writerow({
                'symbol': constituent.get('symbol', ''),
                'name': constituent.get('name', ''),
                'industry': constituent.get('industry', ''),
            })

except requests.exceptions.RequestException as e:
    print(f"Error making the API request: {e}")
except requests.exceptions.HTTPError as e:
    print(f"HTTP Error: {e}")
except requests.exceptions.JSONDecodeError as e:
    print(f"JSON Decode Error: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

